version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: karthikb96/reverseproxy 
  backend_user:
    build:
      context: ../../udagram-api-user
    image: karthikb96/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed 
    image: karthikb96/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend 
    image: karthikb96/udagram-frontend